name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use oxr463/setup-cordova
        uses: oxr463/setup-cordova@0.0.2
        with:
          exec: |
            cordova platform add android && \
            cordova build --no-telemetry && \
            cp "$(find . -name '*.apk')" .
